/* =========================================================
   WHprompts — Shared Data & Storage
   Yeh file index.html aur admin.html dono use karte hain
   ========================================================= */

window.DEFAULT_PROMPTS = [
  { id:1, cat:"Beach", title:"Golden Hour Breeze", prompt:"A beach girl walking barefoot along the shoreline during golden hour. Her hair dances in the sea breeze, and the sunlight kisses her skin with a warm, cinematic glow. Gentle waves reflect orange and pink hues as she smiles naturally toward the lens. Style Keywords: Cinematic | Golden Hour | Natural | Warm | Lifestyle", img:"images/1.jpg" },
  { id:2, cat:"Beach", title:"Tropical Serenity", prompt:"A girl in a white sundress stands near a palm tree, soft shadows falling across her face. The horizon glows with pastel skies, and her gentle expression feels calm and alive, like a dreamy vlog moment. Style Keywords: Soft Pastel | Dreamy | Minimal | Tropical | Calm", img:"images/2.jpg" },
  { id:3, cat:"Beach", title:"Tide Wanderer", prompt:"A man walks shirtless by the tide, jeans rolled up, sunlight reflecting on wet sand. His confident expression and cinematic lighting create a lifestyle-magazine energy. Style Keywords: Cinematic | Confident | Natural | Lifestyle | Warm", img:"images/3.jpg" },
  { id:4, cat:"Beach", title:"Surfer Soul", prompt:"A surfer boy holding his board, eyes squinting into the sun. Salt in his hair, droplets on his skin — raw, real, and wild. Style Keywords: Adventure | Raw | Sporty | Vibrant | Free", img:"images/4.jpg" },
  { id:5, cat:"Beach", title:"Sunset Promise", prompt:"A couple walking hand in hand along the shoreline, waves touching their feet. The sunset paints their silhouettes in soft gold. Style Keywords: Romantic | Cinematic | Warm | Silhouette | Emotional", img:"images/5.jpg" },
  { id:6, cat:"Beach", title:"Playful Waves", prompt:"The couple splashes each other, laughing freely as droplets sparkle in sunlight. Captured in motion, it feels like a travel vlog moment. Style Keywords: Candid | Fun | Dynamic | Vlog | Bright", img:"images/6.jpg" },
  { id:7, cat:"Birthday", title:"Glamorous 28th Birthday", prompt:"Create a glamorous Gemini AI birthday portrait — elegant woman holding a chocolate cake under a warm spotlight, wearing a glittering black gown and silver crown. A cinematic, modern Google Gemini AI photo vibe.", img:"images/7.jpg" },
  { id:8, cat:"Birthday", title:"Fashion Editorial Blazer", prompt:"A stylish Gemini AI photo prompt for birthday — woman in black oversized blazer and sunglasses, holding a cake with lit \"28\" candles. Dramatic lighting and minimal studio background.", img:"images/8.jpg" },
  { id:9, cat:"Birthday", title:"Red-Themed 18th Birthday", prompt:"A stunning AI birthday girl prompt — red satin corset, pearl jewelry, spotlight glow, and cherry-accented cake.", img:"images/9.jpg" },
  { id:10, cat:"Birthday", title:"Black & Gold Birthday (Boy)", prompt:"A confident young man in a black suit with gold balloons — the ultimate Gemini AI birthday boy prompt for cinematic AI photo editing.", img:"images/10.jpg" },
  { id:11, cat:"Birthday", title:"Casual Party Vibes (Boy)", prompt:"A cheerful young man smiling with a cupcake and balloons — a warm, relaxed Google Gemini AI birthday photo.", img:"images/11.jpg" },
  { id:12, cat:"Birthday", title:"City Night Birthday (Boy)", prompt:"A cinematic night backdrop, cake with sparklers, and neon city reflections — a stylish Gemini AI birthday photo prompt.", img:"images/12.jpg" },
  { id:13, cat:"Boy", title:"Retro Bollywood Style", prompt:"A photorealistic portrait of the person from the uploaded image. A dashing South Indian man with a beard and dark hair, wearing yellow-tinted sunglasses, a stylish white three-piece suit (with an open vest revealing necklaces), and multiple rings and bracelets. He is seated on the back of a red convertible car, smiling and looking to the side. The background features a bright blue sky, the ocean, and a cityscape, suggesting a luxurious coastal setting under clear, sunny weather.", img:"images/13.jpg" },
  { id:14, cat:"Boy", title:"K-Drama Campus Hero", prompt:"A photorealistic portrait of the person from the uploaded image. A stylish South Indian man with a beard, sunglasses, and curly dark hair, wearing a red and blue plaid short-sleeved shirt, dark pants, and a satchel across his body. He has wired earphones in, an ID card hanging from a red lanyard, and his hands in his pockets. He is standing in front of a brick wall and a partially visible open door, with another person blurred in the background, suggesting a university or casual urban setting. The lighting is bright and natural.", img:"images/14.jpg" },
  { id:15, cat:"Boy", title:"Cinematic Gangster", prompt:"A photorealistic portrait of the person from the uploaded image. A suave South Indian man with a sleek haircut, a well-groomed beard and mustache, wearing a charcoal grey blazer over a brown leather-collared jacket, a dark patterned tie, and fingerless leather gloves. He is striking a confident pose, looking directly at the viewer with an intense gaze, against a plain light grey studio background. The lighting is even and professional.", img:"images/15.jpg" },
  { id:16, cat:"Boy", title:"Retro Street Vibes", prompt:"Create a retro, vintage-inspired image - grainy yet bright with little sun rays based on the reference picture. The boy should be wearing a light maroon shirt, paired with plated off-white pants styled in a Pinterest-inspired aesthetic. The vibe must capture the essence of a 90s movie dark-brown-haired baddie, hair waving by a windy, romantic atmosphere. Standing under the aesthetic street light and reading a book as a few leaves blow in the air, while dramatic contrasts add mystery and artistry to the scene, creating a moody yet enchanting atmosphere.", img:"images/16.jpg" },
  { id:17, cat:"Boy", title:"Outdoor Casual Tourist", prompt:"A photorealistic portrait of the person from the uploaded image. A young, fit South Indian man with short, dark hair and a light beard, wearing aviator sunglasses and a maroon long-sleeved t-shirt. He has his hands in the pockets of light-colored trousers, standing confidently against a blurred outdoor background featuring a light brown fence and greenery. The lighting is bright and natural.", img:"images/17.jpg" },
  { id:18, cat:"Boy", title:"Corporate Executive", prompt:"A photorealistic portrait of the person from the uploaded image. A handsome South Indian man with a neat beard and mustache, wearing a sharp black suit jacket over a crisp white shirt, and black trousers. He is leaning casually against a dark grey wall with his hands in his pockets, looking at the viewer with a friendly smile. The lighting is soft and even, highlighting the textures of his clothing.", img:"images/18.jpg" },
  { id:19, cat:"Girl", title:"Saree Elegance", prompt:"A beautiful girl wearing a flowing silk saree, traditional Indian jewelry, and soft makeup, standing in a vintage Bollywood studio setting, cinematic lighting, vibrant fabric details, realistic textures, elegant posture, keep original facial features, portrait photography, 9:16 aspect ratio, Instagram aesthetic", img:"images/19.jpg" },
  { id:20, cat:"Girl", title:"Retro 70s Aesthetic", prompt:"A stylish girl in 1970s retro fashion, bold eyeliner, glossy lips, disco-inspired outfit with flared pants, soft grain film effect, neon studio lights, authentic vintage magazine cover look, realistic portrait photography, keep the original face unchanged, 9:16 aspect ratio, aesthetic Instagram vibe", img:"images/20.jpg" },
  { id:21, cat:"Girl", title:"Dreamy Aesthetic", prompt:"A dreamy aesthetic portrait of a girl with pastel tones, soft glowing skin, gentle lighting, whimsical background of blooming flowers, cinematic bokeh, modern Pinterest-inspired look, natural face preserved, elegant and artistic Instagram photo style, 9:16 aspect ratio", img:"images/21.jpg" },
  { id:22, cat:"Girl", title:"Saree Street", prompt:"A trendy girl in a colorful saree walking down an urban street, candid street photography vibe, golden hour sunlight, cinematic lens flare, vibrant city background, realistic portrait with preserved face, modern Bollywood-inspired Instagram look, 9:16 vertical format", img:"images/22.jpg" },
  { id:23, cat:"Girl", title:"Cinematic Rooftop", prompt:"A girl standing on a rooftop at dusk, city skyline behind her, dramatic backlight, warm ambient glow, cinematic film composition, soft haze, natural facial features preserved, high detail, 9:16 aspect ratio, Instagram-ready", img:"images/23.jpg" },
  { id:24, cat:"Girl", title:"Watercolor Portrait", prompt:"Convert this photo into a delicate watercolor illustration: soft brush texture, pastel tones, loose edges, light wash background, natural face preserved, artistic portrait look, vertical format for social media", img:"images/24.jpg" },
  { id:25, cat:"Family", title:"Father–Daughter Portrait", prompt:"Create a realistic father–daughter portrait, the exact same faces as the uploaded image. They are sitting together on a wooden bench in a sunlit garden, smiling warmly at each other. Soft golden-hour lighting, cinematic depth of field, 85mm lens, natural colors, family photo style.", img:"images/25.jpg" },
  { id:26, cat:"Family", title:"Father–Son Photo", prompt:"Generate a natural father–son photo with the same faces as the upload. They are playing catch in the backyard, candid motion, laughing expressions. Bright daylight, sharp focus, realistic skin tones, 4K family photography.", img:"images/26.jpg" },
  { id:27, cat:"Family", title:"Toddler Family Hug", prompt:"Generate a candid toddler hug scene. Parents kneeling down with arms around their child, joyful expressions. Living room setting, warm indoor lights, bokeh effect, natural family moment style.", img:"images/27.jpg" },
  { id:28, cat:"Family", title:"Retro 1970s Family Portrait", prompt:"Create a 1970s retro family portrait, same faces as upload, posed together in a living room with vintage wallpaper and wood furniture. Film grain, Kodak Portra tones, slightly faded colors, classic photo album style.", img:"images/28.jpg" },
  { id:29, cat:"Family", title:"Christmas Family Gathering", prompt:"Create a Christmas family portrait, same faces as uploaded. Everyone gathered around a decorated Christmas tree, cozy sweaters, warm fireplace glow, fairy lights in background, cinematic holiday style.", img:"images/29.jpg" },
  { id:30, cat:"Family", title:"Outdoor Picnic Family Photo", prompt:"Create a cheerful family picnic photo, same faces as uploaded. Sitting on a blanket in the park with baskets of food, candid smiles, bright daylight, fresh green surroundings, ultra-realistic natural tones.", img:"images/30.jpg" },
  { id:31, cat:"Couple", title:"Diwali Fireworks Terrace", prompt:"Diwali Tip: A hyper-realistic 4K cinematic portrait of a young man and a young woman, their faces identical to the reference photo. They stand close together on a terrace on Diwali night. The man, wearing a white kurta, holds a lit firecracker in one hand, looking at it with amusement, while the other is tucked into his pajama pocket. The woman wears a bright yellow embroidered lehenga choli, embellished with mirrors and thread work, accessorized with colorful bracelets, a necklace, and earrings. Her long, dark hair is styled in a unique style, flowing over her shoulders, and her forehead is adorned with an intricate maang tikka. She also holds a glittering firecracker, and golden sparks give her face a festive glow. The background features a night sky filled with fireworks and the terrace walls adorned with gleaming oil lamps. Natural, festive, and highly realistic.", img:"images/31.jpg" },
  { id:32, cat:"Couple", title:"Natural Everyday", prompt:"Combine image 1 (A) and image 2 (B) into a natural couple portrait. Preserve both faces exactly. A slightly left, B slightly right, shoulders touching, relaxed smiles. Soft daylight, subtle backlight, 50mm eye-level shot, realistic skin texture, no filters, no text.", img:"images/32.jpg" },
  { id:33, cat:"Couple", title:"Cinematic Night", prompt:"Merge A and B into a cinematic night couple portrait. Preserve both faces. Neon bokeh in the background, gentle rain reflections on asphalt, soft key light from the left side. 85mm portrait lens, teal-orange grade, film grain finish, romantic atmosphere.", img:"images/33.jpg" },
  { id:34, cat:"Couple", title:"Retro Polaroid", prompt:"Create an image taken with a Polaroid camera. The photo should look like a regular photo, without any clear subject or props. The photo should have a slight blur effect and consistent lighting source, like a flash in a dark room, spread throughout the photo. Do not alter the faces. Replace the background behind the two people with a white curtain. The man is hugging her from the back.", img:"images/34.jpg" },
  { id:35, cat:"Couple", title:"Studio White BG", prompt:"Studio couple portrait of A and B on a pure white background. Preserve both faces. Three-point lighting (key 45° right), soft shadows, gentle skin retouching, neutral color tone, 35mm full-body shot. Natural pose-A's left hand on B's shoulder, B leans slightly toward A.", img:"images/35.jpg" },
  { id:36, cat:"Couple", title:"Pre-Wedding Romance", prompt:"Combine A and B into an elegant pre-wedding portrait. Preserve both faces. Sunset backlight with flowing veil, gentle breeze, minimalistic garden venue. 70mm half-body shot, pastel color grading, cinematic romantic style, like a magazine cover.", img:"images/36.jpg" },
  { id:37, cat:"Father-Daughter", title:"Evening Blessing", prompt:"Father wearing a simple kurta, blessing his 30-year-old daughter in a traditional saree before she leaves home, warm golden sunset light, gentle smiles, cinematic realism.", img:"images/37.jpg" },
  { id:38, cat:"Father-Daughter", title:"Festival of Memories", prompt:"Father and daughter celebrating Diwali together, soft fairy lights in the background, both in elegant ethnic outfits - father in beige kurta, daughter in red silk saree holding diyas, emotional warm tones, sparkle reflections.", img:"images/38.jpg" },
  { id:39, cat:"Father-Daughter", title:"Morning Chai Moments", prompt:"Father and daughter sharing morning tea on a terrace, misty dawn light, laughter in the air, candid realism, fine details.", img:"images/39.jpg" },
  { id:40, cat:"Father-Daughter", title:"Generations of Strength", prompt:"Father teaching his grown daughter how to care for family plants in a small courtyard garden, earthy tones, sunlight filtering through leaves, deep connection.", img:"images/40.jpg" },
  { id:41, cat:"Father-Daughter", title:"Wedding Day Reflection", prompt:"Father helping his daughter adjust her dupatta before her wedding, emotional tears, soft indoor lighting, warm tones, delicate jewelry reflections.", img:"images/41.jpg" },
  { id:42, cat:"Father-Daughter", title:"Cultural Heritage", prompt:"Father and daughter in front of a heritage haveli, both dressed in elegant traditional outfits, proud smiles, natural tones.", img:"images/42.jpg" },
  { id:43, cat:"Father-Son", title:"Urban Cool Studio", prompt:"Transform the uploaded photo into a cinematic, ultra-realistic portrait of a father and son duo. Keep the exact same faces and body proportions as in the uploaded photo. The father wears a fitted black leather jacket over a white tee, dark jeans, and sneakers, seated casually on a metal stool. The 5-year-old son, wearing a white polo shirt, ripped light-blue jeans, and Nike Air Jordan low shoes, sits beside him on a wooden crate, mimicking his father's pose and expression. Both smile confidently under studio lighting with dramatic smoke and a dark gradient background. Make it look like a high-end 8K magazine shoot.", img:"images/43.jpg" },
  { id:44, cat:"Father-Son", title:"Outdoor Lifestyle", prompt:"Create a photo-realistic father and son outdoor portrait, using the uploaded image as the reference for faces and body structure. Both wear matching casual outfits - white shirts, light blue jeans, and white sneakers - standing on a park pathway surrounded by soft golden-hour sunlight and blurred greenery. Keep their facial likeness 100% accurate, with natural skin tones and hair details. Capture a warm, emotional father-son bond with candid smiles, like a professional lifestyle magazine photo.", img:"images/44.jpg" },
  { id:45, cat:"Father-Son", title:"Minimalist B&W Studio", prompt:"Reimagine the uploaded photo into a black-and-white fine-art studio portrait of a father and his 5-year-old son. Maintain identical faces and proportions. Both wear plain white shirts and black trousers, seated close together with relaxed poses. The background is a minimal black studio with subtle directional light emphasizing contours and expressions. Render in ultra 8K clarity, highlighting realism, emotion, and contrast.", img:"images/45.jpg" },
  { id:46, cat:"Father-Son", title:"Polaroid Retro", prompt:"Convert the uploaded image into a retro Polaroid-style portrait of a grown-up father and son, maintaining 100% of their real faces and body proportions from the uploaded photo. Both appear relaxed and smiling, seated side by side on a wooden bench outdoors under soft golden-hour light. The father wears a beige linen shirt with rolled sleeves, and the son wears a light denim jacket over a white T-shirt. Apply a vintage film tone, subtle warm grain texture, and a Polaroid frame border with a soft vignette.", img:"images/46.jpg" },
  { id:47, cat:"Father-Son", title:"Suit-Up Studio", prompt:"Transform the uploaded photo into an ultra 8K hyper-realistic studio portrait of a father and his adult son. Preserve their real faces and builds from the uploaded reference image with perfect likeness. Both wear sharp tailored suits - the father in a dark navy suit with a white dress shirt and silver tie, and the son in a slim-fit black tuxedo with a bow tie. The father sits on a classic stool with a confident smile while the son stands beside him with one hand in his pocket, slightly leaning toward him. Use high-end magazine-style lighting with soft reflections, a matte black studio background, and a hint of rim light.", img:"images/47.jpg" },
  { id:48, cat:"Father-Son", title:"Traditional Indian Studio", prompt:"Convert the uploaded photo into an ultra 8K realistic father and son portrait in traditional Indian attire. Keep the exact same faces and body proportions from the uploaded photo. The father wears a cream-colored silk kurta with golden embroidery and a matching churidar, while the adult son wears a royal blue sherwani with subtle gold patterns and a cream stole draped over his shoulder. Both stand close together, smiling naturally, radiating warmth and confidence. The background is a luxury studio setup with soft warm lighting, muted beige drapes, and a hint of marigold flowers along the floor for a festive touch.", img:"images/48.jpg" },
  { id:49, cat:"Diwali", title:"Man with Phoolihadi", prompt:"Ultra realistic 4K cinematic portrait of the same young man, face exactly like the reference photo. He is standing on a terrace at Diwali night, wearing a white kurta. One hand holds a lit phoolihadi and he looks at it happily, the other hand in pajama pocket. Background shows night sky with fireworks and a terrace wall decorated with glowing diyas. Natural, festive, and highly realistic. Add a metallic \"Happy Diwali\" text in the background.", img:"images/49.jpg" },
  { id:50, cat:"Diwali", title:"Man Lighting Diya (Modern Balcony)", prompt:"Ultra realistic 4K Diwali festival scene, a handsome young man wearing a stylish traditional linen shirt, gracefully lighting an earthen diya lamp. His face must remain exactly the same as in the reference photo (no face change). Background is outdoor with a modern festival look - balcony or terrace decorated with fairy lights, lanterns, glowing candles, flower garlands, and elegant rangoli. Warm golden cinematic lighting, natural skin tone, high-quality standing hand diya.", img:"images/50.jpg" },
  { id:51, cat:"Diwali", title:"Man Lighting Diya (Festival Scene)", prompt:"Ultra realistic 4K Diwali festival scene, a handsome young man wearing a stylish traditional linen shirt, gracefully lighting an earthen diya lamp. His face must remain exactly the same as in the reference photo (no face change). Balcony or terrace decorated with fairy lights, lanterns, glowing candles, flower garlands, and elegant rangoli. Warm golden cinematic lighting, natural skin tone, high-quality upright hand-held diya.", img:"images/51.jpg" },
  { id:52, cat:"Diwali", title:"Man on Rooftop with Diya & Fireworks", prompt:"Do not alter the face. A man in a cream kurta with a silk dupatta stands on a modern rooftop terrace under the night sky. The background is filled with fireworks, fairy lights, and glowing rangoli patterns. A diya flickers gently in his hand, casting warm golden highlights. Shot in DSLR-style sharpness, 4K cinematic effect.", img:"images/52.jpg" },
  { id:53, cat:"Diwali", title:"Elegant Kurta Portrait", prompt:"A hyper-realistic 4K Diwali scene: a handsome young man in a white kurta gracefully lights a clay diya. Face must be identical to the reference photo, with no variations. Festive outdoor atmosphere - balcony or terrace with colored lights, lanterns, glowing candles, garlands, and elegant rangoli. Warm golden cinematic lighting, natural skin tones, high-quality upright hand-held diya.", img:"images/53.jpg" },
  { id:54, cat:"Diwali", title:"Balcony Sparkler Portrait", prompt:"Do not change the face. Young man in a pastel kurta holding a lit sparkler on a balcony at night, city-skyline bokeh and fairy lights in the background, warm golden glow, natural skin tones, ultra-realistic 4K look.", img:"images/54.jpg" },
  { id:55, cat:"Hairstyle", title:"Pixie Cut", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to a pixie cut. Make the new hair look natural, realistic, and consistent with lighting and head shape. Maintain photo-realistic skin texture and full likeness of the original image.", img:"images/55.jpg" },
  { id:56, cat:"Hairstyle", title:"Box Braids", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to box braids. Make the braids appear natural, detailed, and consistent with the lighting and head shape. Preserve realistic texture and authentic likeness.", img:"images/56.jpg" },
  { id:57, cat:"Hairstyle", title:"Wet Hair Look", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to a wet hair look. The new hair should look shiny, sleek, and consistent with studio lighting. Maintain full photo realism, skin detail, and face accuracy.", img:"images/57.jpg" },
  { id:58, cat:"Hairstyle", title:"Buzz Cut", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to a buzz cut. The hair should appear evenly trimmed, sharp, and natural with realistic scalp texture and consistent lighting. Maintain photo-realistic skin tone and true likeness.", img:"images/58.jpg" },
  { id:59, cat:"Hairstyle", title:"Cornrow Braids", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to cornrow braids. The braids should look tight, symmetrical, and cleanly defined, with realistic texture and consistent lighting. Preserve natural skin tone and facial identity.", img:"images/59.jpg" },
  { id:60, cat:"Hairstyle", title:"Slick Back", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to a slick back style. The hair should look neatly combed backward with subtle shine and realistic texture, matching head shape and lighting. Preserve facial detail and realism.", img:"images/60.jpg" },
  { id:61, cat:"Hairstyle", title:"Slick Back", prompt:"Keep the uploaded person's exact face, body, pose, outfit, and background, but change the hairstyle to a slick back style. The hair should look neatly combed backward with subtle shine and realistic texture, matching head shape and lighting. Preserve facial detail and realism.", img:"images/61.jpg" }
  [
  { id:62, cat:"Sci-Fi", title:"Neon Futuristic City Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair, standing in a neon-lit futuristic city. Holographic signs and flying vehicles create dynamic reflections on wet streets. He wears a sleek metallic jacket with subtle glowing trims and slim black pants, blending fashion and futuristic tech aesthetics.\n\nLighting: Multi-colored neon lights — blues, pinks, and purples — reflecting off glass surfaces and his jacket. Rim lighting emphasizes facial features and silhouette.\n\nExpression: Focused, confident, slightly mysterious — a young hero navigating a futuristic urban landscape.\n\nBackground: Blurred sci-fi cityscape with glowing skyscrapers, holographic billboards, and atmospheric haze. Motion blur adds energy and cinematic depth.\n\nCamera: 85mm lens, shallow depth of field — focus on face and upper body, bokeh lights in background.\n\nStyle: Fine art photography, cinematic color grading, editorial sci-fi aesthetic.", img:"images/62.jpg" },
  { id:63, cat:"Fantasy", title:"Enchanted Forest Mystical Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin, wavy dark brown hair, and soft hazel eyes, standing in a misty enchanted forest. Light filters through tall trees, casting ethereal beams across his face and shoulders.\n\nOutfit: Deep green cloak over a fitted dark shirt and slim trousers, flowing naturally in the misty breeze.\n\nLighting: Soft, diffused natural light with cool blue and subtle golden highlights. Fog adds layered depth and cinematic atmosphere.\n\nBackground: Soft-focus forest with mist and faint glowing particles or fireflies. Trees fade into atmospheric haze.\n\nExpression: Calm, introspective, slightly mystical — evoking magical and poetic cinematic mood.\n\nCamera: 85mm lens, shallow depth of field, smooth bokeh blending mist and foliage.\n\nStyle: Fine art photography, cinematic soft lighting, mystical editorial aesthetic.", img:"images/63.jpg" },
  { id:64, cat:"Vintage", title:"Retro City Street Style", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair, standing on a sunlit retro city street with vintage cars and classic storefronts. He wears a mustard yellow corduroy jacket over a white t-shirt, slim brown trousers, and classic leather shoes.\n\nLighting: Warm afternoon sunlight with soft shadows, golden highlights across hair and face for nostalgic cinematic feel.\n\nBackground: Soft-focus 70s city street with vintage cars, brick facades, and faded signage. Subtle motion blur adds dynamic realism.\n\nExpression: Calm, nostalgic, and slightly playful — evoking a romanticized retro cinematic vibe.\n\nCamera: 85mm lens, shallow depth of field — focus on face and upper body, background softly blurred.\n\nStyle: Fine art photography, cinematic warm tones, editorial retro aesthetic.", img:"images/64.jpg" },
  { id:65, cat:"Adventure", title:"Golden Desert Sunset Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with sun-kissed fair skin and wavy dark brown hair, standing atop a sand dune in a golden desert at sunset. Wind tousles his hair and flowing scarf. He wears a lightweight cream tunic and slim brown trousers, evoking adventure and timeless heroism.\n\nLighting: Warm golden sunlight casting long dramatic shadows and highlights across his face and silhouette.\n\nBackground: Soft-focus desert horizon with rolling dunes, glowing in shades of gold, orange, and peach.\n\nExpression: Calm, heroic, slightly contemplative — capturing epic cinematic solitude.\n\nCamera: 85mm lens, shallow depth of field — focus on face and upper body, soft cinematic bokeh blending the desert.\n\nStyle: Fine art photography, cinematic warm tones, editorial adventure aesthetic.", img:"images/65.jpg" },
  { id:66, cat:"Ethereal", title:"Dreamy Underwater Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair floating gently underwater. Sunlight filters from the surface, creating refracted patterns on his face. He wears a flowing white shirt that moves with the water, evoking a dreamy, ethereal mood.\n\nLighting: Soft underwater sunlight, subtle blue-green hues, gentle highlights and shadows enhancing contours.\n\nBackground: Soft-focus water environment with particles floating, creating dreamy cinematic depth.\n\nExpression: Calm, serene, slightly introspective — as if suspended in a poetic underwater world.\n\nCamera: 85mm lens, shallow depth of field — focus on eyes and face, water movement softly blurred.\n\nStyle: Fine art photography, cinematic soft tones, ethereal editorial aesthetic.", img:"images/66.jpg" },
  { id:67, cat:"Urban", title:"Vibrant Festival Night Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair, standing amid a vibrant festival at night. Neon signs, lanterns, and colorful lights reflect across his face. He wears a sleek bomber jacket and slim black pants, blending modern fashion with festive energy.\n\nLighting: Multi-colored neon lights — pink, blue, purple, and amber — creating reflections and cinematic depth.\n\nBackground: Blurred festival crowd, glowing lanterns, and motion blur from moving lights.\n\nExpression: Excited, joyful, yet introspective — capturing the energy and intimacy of a cinematic festival moment.\n\nCamera: 85mm lens, shallow depth of field, focus on face with soft bokeh of neon lights.\n\nStyle: Fine art photography, cinematic color grading, editorial urban-night aesthetic.", img:"images/67.jpg" },
  { id:68, cat:"Urban", title:"Rain-Soaked Urban Night Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair, standing on a rain-soaked city street at night. Neon signs reflect on wet pavement, small raindrops glistening on his coat. He wears a dark trench coat over a black shirt and slim trousers.\n\nLighting: High-contrast cinematic lighting — warm amber streetlights against cool neon blues and magentas, with subtle rim lighting highlighting hair and face.\n\nBackground: Soft-focus urban street with reflections, distant neon signs, and slight fog for atmospheric depth.\n\nExpression: Intense, introspective, slightly melancholic — capturing cinematic emotion in a high-fashion urban setting.\n\nCamera: 85mm lens, shallow depth of field, focus on eyes and face, bokeh blending reflections and rain.\n\nStyle: Fine art photography, cinematic color grading, editorial urban-night aesthetic.", img:"images/68.jpg" },
  { id:69, cat:"Winter", title:"Snowy Winter Elegance Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin and wavy dark brown hair, standing in a softly falling snow. His hair and coat show subtle frost touches. He wears a dark wool coat over a turtleneck, slim trousers, and gloves, evoking cozy elegance.\n\nLighting: Cool natural light with soft blue and silver tones. Rim lighting highlights hair and shoulders against the snow.\n\nBackground: Soft-focus snow-covered trees, snowflakes blurred in foreground for cinematic depth.\n\nExpression: Calm, introspective, serene — evoking quiet winter poetry.\n\nCamera: 85mm lens, shallow depth of field — focus on face and upper body, cinematic bokeh blending snow.\n\nStyle: Fine art photography, muted cool tones, editorial cinematic winter aesthetic.", img:"images/69.jpg" },
  { id:70, cat:"Coastal", title:"Ocean Cliff Heroic Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin, wavy brown hair tousled by strong seaside wind, standing on cliffs overlooking the ocean. He wears a beige trench coat and slim navy pants, coat flaring dynamically in the wind.\n\nLighting: Golden-hour sunlight with warm highlights on hair and face, ocean spray catching light for dramatic shimmer.\n\nBackground: Soft-focus waves crashing on cliffs, distant horizon fading into cinematic mist.\n\nExpression: Thoughtful, heroic, and slightly nostalgic — cinematic adventure by the sea.\n\nCamera: 85mm lens, shallow depth of field — focus on eyes and face, bokeh blending waves and sky.\n\nStyle: Fine art photography, cinematic golden tones, editorial coastal aesthetic.", img:"images/70.jpg" },
  { id:71, cat:"Vintage", title:"Classic Car Elegance Portrait", prompt:"Reference: Use the person’s face and slim body from the reference image.\n\nPrompt: Hyper-realistic cinematic portrait of a young man with fair skin, wavy brown hair styled naturally, leaning casually on a polished vintage car. He wears a tailored navy blazer over a white shirt, slim black trousers, and polished boots.\n\nLighting: Warm golden light reflecting off the car, soft shadows enhancing depth, subtle rim light outlining silhouette.\n\nBackground: Soft-focus retro street scene with cobblestones, blurred buildings, and ambient sunlight.\n\nExpression: Calm, confident, stylish — exuding luxury lifestyle and cinematic elegance.\n\nCamera: 85mm lens, shallow depth of field — focus on face and upper body, smooth bokeh highlighting car and street.\n\nStyle: Fine art photography, cinematic warm tones, editorial high-fashion aesthetic.", img:"images/71.jpg" },
  { id:72, cat:"Fashion", title:"Colorful Studio Fashion Editorial", prompt:"Reference: Keep the same boy’s face and slim, elegant body.\n\nPrompt: Hyper-realistic cinematic fashion portrait of a 20-year-old boy sitting casually on a low modern chair in a luxurious, colorful studio. The floor is glossy black marble reflecting vivid neon lights. Behind him, abstract light beams in pink, teal, and electric blue create a futuristic backdrop with cinematic haze.\n\nOutfit: Striking street-luxury style — cropped white puffer jacket with metallic purple sheen, paired with sleek black cargo pants and high-top sneakers. A thin silver chain and ring complete the look.\n\nPose: One leg crossed over the other, leaning slightly to the side with one hand resting on his knee, the other brushing back his hair. His gaze is calm yet powerful — editorial confidence.\n\nLighting: Three-point cinematic lighting — magenta glow from the left, teal fill from the right, and soft warm rim light outlining his silhouette. Reflections on the marble floor enhance depth and vibrancy.\n\nBackground: A color-rich studio with geometric neon shapes and soft mist for cinematic flair — evoking a premium fashion campaign or a music video editorial.\n\nMood: Bold, youthful, and high-end — combining streetwear aesthetics with cinematic artistry.\n\nCamera: 50mm lens, low angle, slightly tilted composition for dynamic depth. Ultra-realistic textures on face, outfit, and reflections.\n\nStyle: Colorful cinematic editorial with luxury-meets-street vibe — energetic yet polished atmosphere.\n\nImportant: Keep the boy’s facial features 100% identical and realistic.", img:"images/72.jpg" },
  { id:73, cat:"Fashion", title:"Vivid Color Gradient Studio Portrait", prompt:"Reference: Keep the same boy’s face and slim, elegant body.\n\nPrompt: Hyper-realistic cinematic portrait of a 20-year-old boy standing confidently in the middle of a luxury studio setup. The floor reflects vivid tones of orange, cyan, and violet lights blending smoothly like a music video set. Misty air enhances the cinematic depth.\n\nOutfit: Vibrant street-luxury look — glossy teal bomber jacket over a soft white T-shirt, paired with beige trousers and clean white sneakers. A sleek silver chain and wristwatch add subtle elegance.\n\nPose: Standing with one hand in pocket and the other holding sunglasses near his face. His posture is relaxed but charismatic — eyes slightly squinting toward the lens, exuding quiet confidence.\n\nLighting: Colorful cinematic tri-light scheme — warm orange from the left, cool blue from the right, and gentle magenta backlight creating a vivid halo. Soft shadows fall across the floor for high-end editorial balance.\n\nBackground: Large gradient color walls fading from deep violet to cyan, with subtle light streaks and particles floating to create motion and atmosphere.\n\nMood: Energetic yet refined — a fusion of fashion editorial and cinematic storytelling. The colors feel alive, like a high-end GQ or Vogue campaign.\n\nCamera: Mid-shot with shallow depth of field, 85mm lens, soft focus on background lights for dreamy cinematic effect.\n\nStyle: Bold, colorful, luxurious — representing confidence, youth, and premium modern aesthetics.\n\nImportant: Keep his face 100% accurate and realistic.", img:"images/73.jpg" },
  { id:74, cat:"Fashion", title:"Royal Blue Monochrome Editorial", prompt:"Reference: Keep the same boy’s face and slim, elegant body.\n\nPrompt: Hyper-realistic cinematic fashion portrait of a 20-year-old boy standing in a minimalist studio bathed entirely in deep royal blue tones. The environment, lighting, and reflections all harmonize around this single color, creating a monochrome cinematic masterpiece.\n\nOutfit: Sleek all-blue outfit — a matte navy trench coat over a light blue turtleneck, tailored trousers, and polished blue leather shoes. A subtle silver ring and bracelet add minimal luxury accents.\n\nPose: Standing confidently with both hands in pockets, slightly angled to the side, one foot forward. His gaze meets the camera with calm assurance and cinematic intensity.\n\nLighting: Soft diffused blue light with a subtle rim highlight along the face and shoulders to define contours. Slight reflective sheen on the floor gives depth and elegance. Gentle haze adds atmosphere.\n\nBackground: Smooth monochromatic gradient wall shifting from deep indigo at the top to lighter blue at the bottom, enhancing focus on the subject's silhouette.\n\nMood: Sophisticated, moody, and editorial — merging simplicity with visual depth. Feels like a luxury perfume or fashion campaign.\n\nCamera: Mid-length portrait, 85mm lens, shallow depth of field to blur background softly and emphasize the subject's calm, striking expression.\n\nStyle: Fine art monochrome fashion photography — minimalist yet powerful, cinematic yet timeless.\n\nImportant: Keep his face 100% accurate and realistic.", img:"images/74.jpg" },
  { id:75, cat:"Casual", title:"Sunlit Park Casual Styling", prompt:"Use the reference image for the person's face and slim body.\nOutfit: stylish casual — light beige shirt with rolled sleeves and fitted navy chinos, relaxed yet refined look.\nHair: short, wavy, dark brown, slightly tousled by the park breeze, catching the natural sunlight.\nPose: standing casually near a park pathway, one hand in pocket, the other brushing through hair, body angled toward the camera with a calm confident vibe.\nBackground: lush green park filled with tall trees, soft sunlight filtering through leaves, scattered benches and distant people enjoying the day.\nLighting: warm natural sunlight with soft shadows, gentle highlights on hair and face, subtle golden reflections on ground and outfit.\nExpression: calm, confident, slightly smiling — projecting peaceful, stylish charm.\nAtmosphere: serene, cinematic, natural — blending relaxed lifestyle with elegant outdoor energy.\nKeep the face and slim body consistent with the reference image.", img:"images/75.jpg" },
  { id:76, cat:"Casual", title:"City Park Bench Casual Portrait", prompt:"Use the reference image for the person's face and slim body.\nOutfit: modern street casual — olive-green bomber jacket over white t-shirt and black slim jeans, paired with white sneakers for a trendy relaxed look.\nHair: short, slightly messy, dark brown, moving softly with the breeze.\nPose: sitting on a wooden park bench, one arm resting on the backrest, legs crossed casually, head turned slightly toward the sunlight.\nBackground: spacious city park with green lawns, blooming flowers, and tall trees swaying in the wind, distant people jogging or walking dogs.\nLighting: soft afternoon light with golden tones, subtle shadows on the ground, gentle highlights reflecting off the jacket and hair.\nExpression: thoughtful, relaxed, slightly smiling — radiating peace and confidence.\nAtmosphere: calm, cinematic, urban-natural — blending modern style with nature's quiet charm.\nKeep the face and slim body consistent with the reference image.", img:"images/76.jpg" },
  { id:77, cat:"Beach", title:"Golden Beach Sunset Walk", prompt:"Use the reference image for the person's face and slim body.\nOutfit: relaxed vacation style — light blue linen shirt half unbuttoned, white rolled-up trousers, and barefoot on soft sand.\nHair: short, wavy, dark brown, slightly tousled by the sea breeze, glimmering under sunset light.\nPose: walking slowly along the shoreline, one hand in pocket, the other brushing through hair, body turned partly toward the camera.\nBackground: golden beach at sunset, soft waves touching the shore, orange and pink sky blending over the calm ocean.\nLighting: warm sunset glow illuminating the face and shoulders, gentle rim light from the sun behind, subtle reflections on wet sand.\nExpression: peaceful, confident, slightly smiling — enjoying a quiet moment of freedom.\nAtmosphere: cinematic, tranquil, luxurious — blending natural beauty with effortless style.\nKeep the face and slim body consistent with the reference image.", img:"images/77.jpg" },
  { id:78, cat:"Vintage", title:"Vintage Sunset Aesthetic", prompt:"Apply this prompt to my uploaded image Dreamlike cinematic portrait of a young man with tousled black hair, wearing a knitted white oversized shirt made of soft textured fabric. A single Silver thin necklace enhances his style. His sunglasses create a cool aura as he lowers his head gently. Sunlight in warm amber tones brushes his face and shoulder, glowing against a neutral cream wall. Preserve 100% facial characteristics as attached image.", img:"images/78.jpg" },
  { id:79, cat:"Urban", title:"Aesthetic Pose with Bike", prompt:"A photorealistic night shot of a handsome young Asian man sitting casually on a custom black café racer motorcycle. He has messy, styled black hair and is looking at the camera with a confident, slight smile while crossing his arms. He is wearing a black long-sleeve button-up shirt, dark grey ripped skinny jeans with knee slits, and black and white high-top sneakers. A patterned bandana is tied around his thigh. A glossy black helmet sits on the motorcycle's fuel tank. The bike features chunky tires with white lettering on the sidewalls. The background is an urban street at night with concrete barriers, metal railings, and streetlights illuminating the scene. High quality, flash photography aesthetic, urban vibe. 100% same face as reference person.", img:"images/79.jpg" },
  { id:80, cat:"Urban", title:"Bike Pose", prompt:"A 5'7\" young man with a slim fit rides his black Royal Enfield Bullet 350 with confidence, glancing to the side. He's styled in an oversized white linen shirt, light blue baggy jeans, and white Nike Air Force 1 sneakers, accessorized with classy sunglasses and a silver wristwatch. His face is preserved exactly as is. The image features a vintage Leica M11 Monochrome-inspired aesthetic with deep contrast and motion blur.", img:"images/80.jpg" },
  { id:81, cat:"Urban", title:"Minimalist Aesthetic Car Pose", prompt:"Create an High-contrast nighttime street photograph with a gritty underground Japanese car culture aesthetic. Subject stands casually leaning against a white Audi shot with harsh on-camera flash. Urban alley setting with graffiti-covered concrete walls, dark industrial background. Subject wears oversized dark streetwear: loose blue jeans, textured dark sweater, casual stance with hands relaxed. 100% same face as reference person", img:"images/81.jpg" },
  { id:82, cat:"Casual", title:"Mirror Selfie", prompt:"Aesthetic cozy mirror selfie of a young man sitting casually on a chair, wearing a dark oversized hoodie and blue jeans, holding a I phone 17 in one hand, other other hand resting naturally. Warm beige indoor background with soft studio lighting, minimal modern interior. Cute cartoon-style doodles around her including a smiling sunflower character and hand-drawn yellow sun, playful white sketch lines around the camera.  \nHandwritten romantic, 100% same face as reference person.", img:"images/82.jpg" },
  { id:83, cat:"Casual", title:"Aesthetic Mirror selfie", prompt:"A soft lo-fi aesthetic mirror selfie of a young man based on the provided reference image, preserving 100% identical facial identity, hairstyle, skin tone, and facial proportions. He sits casually on the edge of a low bed, slightly leaning back with a relaxed posture.  \nHe wears a light grey oversized zip-up hoodie layered over a white T-shirt with loose black sweatpants, giving a relaxed streetwear vibe. In one hand he holds a modern smartphone with a clear case, taking a mirror selfie while the other hand rests loosely on the bed beside him.  \nThe environment is a cozy lavender-toned bedroom with soft curtains, a glowing desk lamp, and a few minimal posters on the wall. The mirror has subtle smudges and reflections, adding realism. Warm ambient lighting mixed with cool purple neon glow creates a dreamy night-time aesthetic.  \nAround the mirror are cute hand-drawn doodles such as tiny stars, smiling moon characters, floating hearts, and playful white sketch outlines around the phone and mirror edges. Small handwritten romantic phrases appear on the mirror like “you matter”, “soft moments”, and little sparkles.  \nUltra-detailed cinematic lifestyle photography, natural skin texture, shallow depth of field, cozy lo-fi atmosphere, aesthetic Instagram style composition, 18K ultra-realistic portrait quality.", img:"images/83.jpg" },
  { id:84, cat:"Vintage", title:"Vintage Mirror Selfie", prompt:"A stylish young boy taking a mirror selfie wearing a sky white and black colored loose shirt and white pants holding the shirt casually with one hand minimal jewelry curly hair realistic lighting, and soft white outline glow around him The background is a modern grayscale aesthetic collage with elements like electric guitar headphones dice, cat face decor 3D stars and \"ViKAS\"graffiti text Artistic trendy, Instagram style edit with balanced composition and HD qual.", img:"images/84.jpg" },
  { id:85, cat:"Urban", title:"City Rooftop Sunset Aesthetic", prompt:"A youngboy realistic face taking a mirror selfie,( same face 100%) wearing a coffee loose shirt and white pants, silver chain , Wolf Cut/Mullet hair, realistic lighting, and soft white outline glow around him. The background is a warm, light brown aesthetic featuring cute, illustrated elements: a peek-a-boo teddy bear face in the top left, multiple textured dark brown heart shapes scattered throughout", img:"images/85.jpg" },
  { id:86, cat:"Cinematic", title:"Night Mirror Selfie", prompt:"Cinematic portrait photography, motion blur crowd effect, urban stillness aesthetic, modern editorial style, minimal fashion mood, emotional realism, street photography vibes, fine art portrait, contemporary visual storytelling, high fashion editorial look, moody color grading, depth and motion contrast, subject isolation technique, viral visual composition, cinematic framing, artistic photography style. 100% same face as reference person.", img:"images/86.jpg" },
  { id:87, cat:"Vintage", title:"Classic Car Garage Aesthetic", prompt:"Create a moody mysterious portrait of my picture.\nKeep the same background and camera angle as per the reference warm golden hour sunlight casting dramatic shadow on a plain wall ensure the strong shadow of the face on the wall is visible ratio 9:16 overall cinematic tone.\nDo not change the pose or any kind of detail, just add sunlight", img:"images/87.jpg" },
  { id:88, cat:"Vintage", title:"Grunge Flannel Look", prompt:"Use my uploaded face reference without altering it. Ultra realistic cinematic 8K full-body portrait of me, a 20-year-old Indian man in a white suit with black shirt, holding a bouquet of red roses. Dark background with a golden beam of sunlight casting dramatic shadows. In the shadow, a faint silhouette of a young woman appears, as if I am holding her hand. My eyes are closed, expression calm and serene. Shadow young woman holding the hand and boy hand my eyes closed emotion", img:"images/88.jpg" },
  { id:89, cat:"Vintage", title:"Hip-Hop Street Style", prompt:"RETRO VINTAGE CINEMATIC PORTRAIT WITH SOFT FILM GRAIN AND BRIGHT EXPOSURE, INSPIRED BY A 1990S ROMANTIC CRIME-FILM AESTHETIC. A CONFIDENT MAN WEARING A DEEP CHARCOAL TAILORED SUIT WITH RETRO WIDE-LEG PANTS, HOLDING A SMALL FLOWER BOUQUET IN ONE HAND. WIND MOVES THROUGH HIS HAIR AND SUIT FABRIC, ROMANTICIZING THE MOMENT. HE STANDS AGAINST A SOLID DEEP-SHADOW BACKGROUND, HIGH-CONTRAST DRAMA. WARM GOLDEN-HOUR SUNSET LIGHTING, AMBER HIGHLIGHTS, MYSTERIOUS AND ARTISTIC MOOD, ANALOG FILM LOOK, PINTEREST-STYLE EDITORIAL.", img:"images/89.jpg" },
  { id:90, cat:"Vintage", title:"Denim Jacket Aesthetic", prompt:"A cinematic portrait of a young man with messy curly hair partially covering his eyes, standing confidently with hands in pockets, wearing a plain off-white oversized t-shirt and dark trousers. He is leaning against a classic red vintage sports car (1960s Porsche-style), glossy finish, round headlights visible. Dramatic red and orange backlighting illuminates a textured brick wall behind him, creating a moody, intense atmosphere.", img:"images/90.jpg" },
  { id:91, cat:"Vintage", title:"Disposable Camera Snapshot", prompt:"An ultra-realistic artistic portrait captures the same Indian adult man from the reference photo, with identical face, facial structure, and features preserved — no change in identity. He stands against a plain neutral wall, where warm natural sunlight filters in to form clean geometric shadows, creating a minimal yet cinematic atmosphere.  \nStyled in a perfect black suit with classic vintage trousers, the look blends romantic retro charm with high-fashion editorial aesthetics. The image has a soft grain with bright highlights, evoking a nostalgic ’90s movie vibe. He holds a bunch of red roses in one hand, while the other rests casually in his pocket, subtly romanticizing the calm, sunlit environment with an effortless Valentine mood.", img:"images/91.jpg" },
  { id:92, cat:"Vintage", title:"Skater Style", prompt:"An ultra-realistic portrait captures the same person from the reference photo, with identical face and features preserved, no change in identity. He stands against a plain neutral wall, where warm sunlight filters through to create striking geometric shadows. His  outfit consists of a loose-fit crisp white shirt, tucked slightly into relaxed baggy brown trousers, embodying a refined high-fashion editorial style. 100% same face as reference person.", img:"images/92.jpg" },
  { id:93, cat:"Vintage", title:"Varsity Jacket Aesthetic", prompt:"Cinematic low-angle shot of a person with slightly wind-blown hair and a sharp side profile, sitting relaxed on the roof frame of a white vintage sedan race car. Looking off into the distance. Wearing the exact same outfit as in the uploaded reference photo and CONVERSE Chuck 70 High unisex sneakers in black. The car features racing decals and stickers on the side door. Background is a dramatic solid teal-grey overcast sky. Streetwear aesthetic, automotive lifestyle photography, soft natural lighting, film grain, high definition.  \nPreserve all facial features and expressions exactly as in the original reference. Do not alter identity or proportions. Master realism base applied with hidden signature 69 subtly integrated in micro details, not immediately noticeable. Ratio 3:4.", img:"images/93.jpg" },
  { id:94, cat:"Vintage", title:"Mall Photoshoot Backdrop", prompt:"Create a retro vintage grainy but bright image of the reference picture styled shirt have horizontal lines printed and jeans pant shite sports shoes , slightly loose and worn, giving a 90s movie vibe. The man is standing and laying casually on a classic colored car near the headlights, romanticising the windy outdoor environment. The scene must feel cinematic, with deep shadows and contrast drama, warm\" with same exact face", img:"images/94.jpg" },
  { id:95, cat:"Vintage", title:"Windbreaker Tracksuit Style", prompt:"Create a retro vintage grainy but bright mage of the reference picture but draped in a perfect white colour suit Pinteresty aesthetic retro pants. It must feel like a '90s movie hair baddie with a small flower bookey in hand and romanticising a windy environment. The man is standing against a solid deep shadow and contrast drama, creating a mysterious and artistic atmosphere where the lighting is warm with golden tones evoking a sunset  \nor golden hour alow", img:"images/95.jpg" },
  { id:96, cat:"Nature", title:"Nature & Love", prompt:"Portrait of a young man sitting on a green hillside, looking up at the sky. Wearing a loose T-shirt and dark pants. In the background are giant cumulus clouds, impressive with a golden afternoon bottom. Foreground is filled with colorful wildflowers (orange, white, purple). Taken during the golden hour, the image is extremely detailed, with the man in sharp focus, shallow depth of field, and high resolution. Don't change the face Make messy hair like Korean wear White linen shirt", img:"images/96.jpg" },
  { id:97, cat:"Nature", title:"Nature & Car Style", prompt:"A hyper-realistic, high-fashion portrait of a stylish young man sitting in the driver's seat of a green luxury convertible BMW. He is wearing a pastel lavender shirt and ripped black jeans. Cinematic golden hour lighting with strong sun-flare coming from the trees in the background. Ultra-vibrant green forest bokeh. Sharp focus on the face with smooth", img:"images/97.jpg" },
  { id:98, cat:"Vintage", title:"Vintage Film Aesthetic", prompt:"A stylish young man in a white shirt with a black trauser, standing against a vibrant bhagva colour wall, posing confidently. Above him hangs a modern black pendant lamp casting soft light. Behind him, a large framed photo shows he's in a purple  swetshirt surrounded by greenery, with smaller photo frames arranged asymmetrically on the wall displaying different portraits of he's in outdoor settings. The composition is creative and editorial", img:"images/98.jpg" },
  { id:99, cat:"Casual", title:"Dreamy Mirror Selfie", prompt:"A stylish young man taking a mirror selfie in a modern, minimalistic bathroom. He is wearing a peach knitted oversized sweater with a silver chain necklace, light blue ripped jeans, and a white undershirt peeking out. He holds a smartphone in one hand and poses casually with a slight smile. The background features white tiled walls, a glowing and a green indoor plant adding contrast. Soft lighting enhances the cozy and trendy aesthetic, perfect for a lifestyle or fashion portrait", img:"images/99.jpg" },
  { id:100, cat:"Vintage", title:"Vintage 90s Love", prompt:"Use my uploaded face reference without altering it. Ultra realistic cinematic 8K full-body portrait of me, a 20-year-old Indian man in a white suit with black shirt, holding a bouquet of red roses. Dark background with a golden beam of sunlight casting dramatic shadows. In the shadow, a faint silhouette of a young woman appears, as if I am holding her hand. My eyes are closed, expression calm and serene. Shadow young woman holding the hand and boy hand my eyes closed emotion", img:"images/100.jpg" },
  { id:101, cat:"Vintage", title:"Retro 90s Polaroid Style", prompt:"Use the reference person’s exact face (no changes). Full-body portrait of a young man standing casually with hands in pockets, wearing an olive green overshirt, white t-shirt, beige pants, and white sneakers. Background: cozy plant-filled café with hanging warm paper lanterns, fairy lights, and lush greenery. Soft warm lighting, shallow depth of field, cinematic bokeh. Centered composition, relaxed pose, natural expression, ultra-realistic, 85mm lens, f/1.8.", img:"images/101.jpg" },
  { id:102, cat:"Vintage", title:"Vintage Car Aesthetic", prompt:"ULTRA-REALISTIC 8K CINEMATIC PORTRAIT [KEEP IT REAL FACE FROM UPLOADED IMAGE] OF A STYLISH YOUNG MAN SITTING IN THE DRIVER'S SEAT OF A CLASSIC BRIGHT red CONVERTIBLE CAR. HE IS WEARING A CREAM BEANIE AN OVERSIZED WHITE AND ELECTRIC red GRAPHIC JERSEY, AND BAGGY DARK WASH DENIM JEANS. HE HAS ONE HAND ON THE STEERING WHEEL AND THE OTHER RESTING ON THE DOOR FRAME, LOOKING DIRECTLY INTO THE CAMERA WITH A CONFIDENT EXPRESSION. THE CAR FEATURES A VIBRANT red LEATHER INTERIOR AND POLISHED CHROME DETA", img:"images/102.jpg" },
  { id:103, cat:"Editorial", title:"Black and White Editorial", prompt:"Give the exact same face 8k ultra image.\"A cinematic low angle shot of a stylish man , black and white photography, dramatic side lighting (rim lighting) that highlights his facial features, pitch-black background, high contrast, moody atmosphere, captured on 85mm lens, 8k resolution, ultra-realistic.\"wear black sunglasses.", img:"images/103.jpg" },
  { id:104, cat:"Editing", title:"Red Gangster Poster", prompt:"Glooomyboy Create a cinematic digital illustration of the person in the reference photo. Maintain the exact face identity, hairstyle, expression, skin tone and pose with zero distortion.Transform the entire scene into a deep red high contrast Tamil gangster movie poster style.Replace the background with red gradients, smoky atmosphere and subtle textures. Add bold comic book shading, thick outlines, strong black shadows and glossy highlights on the skin and clothes", img:"images/104.jpg" },
  { id:105, cat:"Editing", title:"Vintage Courtyard Portrait", prompt:"[1/4] A high-quality, authentic-style photograph of a young Indian man(image-1, image-2, image-3, image-4) sitting casually on an old, weathered concrete and tiled step. The setting is the courtyard of a vintage building, featuring aged architectural columns and wall panels painted in a faded, dusty pink and teal-green color palette. Several large, potted green plants in terracotta pots line the ledge behind him.", img:"images/105.jpg" },
  { id:106, cat:"Editing", title:"Red Suit Portrait", prompt:"Use 1st reference image as exclusive facial reference. Absolute face lock. Preserve identity with zero deviation: identical eyes, eyelids, brows, nose structure, lips, jawline, cheekbones, facial proportions, skin texture, pores, facial hair density, beard shape, hairline, and hairstyle. No beautification, no symmetry correction, no smoothing, no stylization. No identity drift under any condition\n\nHair take reference from uploaded image\n\nAnd match the cinematic style, lighting and background of Image 2 create A dramatic graphic-novel realism cinematic digital painting of a confident south Asian man wearing a black tailored suit, white shirt, and black tie, sharp masculine jawline, rugged stubble, strong facial structure, dark round sunglasses like daredevil character, calm dominant expression, head slightly raised, harsh cinematic side lighting with deep chiaroscuro shadows, gritty painterly texturikes subtle grain, realistic skin pores, deep blood-red textured background, minimalist", img:"images/106.jpg" },
  { id:107, cat:"Editing", title:"Poster Collage Design", prompt:"A VERTICAL POSTER COLLAGE DESIGN. THE BACKGROUND CONSISTS OF FOUR STACKED HORIZONTAL ROUNDED RECTANGLES. INSIDE THESE PANELS ARE BLACK AND WHITE CINEMATIC SHOTS OF A YOUNG MAN WITH NORMAL HAIR AND SUNGLASSES IN VARIOUS POSES. SUPERIMPOSED IN THE FOREGROUND ON THE LEFT SIDE IS A FULL-COLOR, HIGH-QUALITY CUTOUT OF THE SAME MAN WEARING  PINK MAUVE SHIRT AND SUNGLASSES, STRIKING A COOL POSE. THE FOREGROUND FIGURE HAS ATHICK WHITE STICKER-STYLE OUTLINE", img:"images/107.jpg" },
  { id:108, cat:"Editing", title:"Yellow Suit Portrait", prompt:"Use 1st reference image as exclusive facial reference. Absolute face lock. Preserve identity with zero deviation: identical eyes, eyelids, brows, nose structure, lips, jawline, cheekbones, facial proportions, skin texture, pores, facial hair density, beard shape, hairline, and hairstyle. No beautification, no symmetry correction, no smoothing, no stylization. No identity drift under any condition\n\nHair take reference from uploaded image\n\nAnd match the cinematic style, lighting and background of Image 2 create A dramatic graphic-novel realism cinematic digital painting of a confident south Asian man wearing a black tailored suit, white shirt, and black tie, sharp masculine jawline, rugged stubble, strong facial structure, dark round sunglasses like daredevil character, calm dominant expression, head slightly raised, harsh cinematic side lighting with deep chiaroscuro shadows, gritty painterly texturikes subtle grain, realistic skin pores, deep blood-red textured background, minimalist, dark yellow lighting color theme.", img:"images/108.jpg" },
  { id:109, cat:"Editing", title:"Streetwear Collage", prompt:"An editorial poster-style multi-panel collage presents Subject[person in the image, quiff-style tousled mid length black hair, light mustache] across three asymmetric photographic frames, unified by a muted-brown urban streetwear aesthetic and a retro analog-digital fusion mood.The top-left frame captures a reflective window shot where the subject holds a phone in front of  with black rectangular sunglasses", img:"images/109.jpg" },
  { id:110, cat:"Editing", title:"Creative Wall Portrait", prompt:"A stylish young man in a white shirt with a black trauser, standing against a vibrant bhagva colour wall, posing confidently. Above him hangs a modern black pendant lamp casting soft light. Behind him, a large framed photo shows he's in a purple  swetshirt surrounded by greenery, with smaller photo frames arranged asymmetrically on the wall displaying different portraits of he's in outdoor settings. The composition is creative and editorial", img:"images/110.jpg" },
  { id:111, cat:"Editing", title:"Wildflower Portrait", prompt:"Same person (reference), sitting in a wildflower field, wearing a loose white shirt and gray pants, holding a white rose, looking down, soft natural sunlight, shallow depth of field, cinematic, high detail", img:"images/111.jpg" },
  { id:112, cat:"Editing", title:"Guitar Street Portrait", prompt:"Ultra-realistic cinematic black and white portrait of the reference person holding an acoustic guitar on shoulder, wearing black leather jacket and black t-shirt, standing in front of a street wall covered with layered Hindi posters and signboards, looking slightly downward, messy medium-length hair, light beard, moody expression, shallow depth of field, soft dramatic lighting, high contrast, 85mm lens, film grain, natural skin texture, exact same face identity, no face change, no beautification, realistic street photography", img:"images/112.jpg" },
  { id:113, cat:"Editing", title:"Sports Press Portrait", prompt:"A hyper-realistic, editorial sports press portrait of the exact same man from the uploaded reference photo (use the uploaded image as the ONLY identity source — absolute identity lock).\n\nHe is shown in a tight medium close-up (head + upper chest visible), standing slightly angled with his shoulders turned, while his face is turned forward but his eyes are looking off to the side with a serious, calm, focused expression.\n\nHis facial identity must be 100% identical to the reference: same bone structure, jawline, cheekbones, nose shape, lips, eye spacing, eyebrow thickness, skin texture, pores, and the exact same hairstyle and hairline.\n\nHe is wearing a formal black suit jacket with a clean sharp fit, a white dress shirt, a black tie, and a white pocket square.", img:"images/113.jpg" },
  { id:114, cat:"Cinematic", title:"Cinematic Red Portrait", prompt:"USE THE IMAGES UPLOADED AS YOUR REFERENCE FOR FACE FEATURES, HAIRSTYLE AND MAKE A CINEMATIC EDITORIAL FASHION PORTRAIT OF A MAN, HEAVY MOTION BLUR EFFECT, SPEED LINES. WEARING A FUŻY RIBBED KNIT SWEATER WITH HORIZONTAL CREAM, GREY AND BLACK STRIPES. MESSY HAIR, SUNGLASSES.SUN-DRENCHED LIGHTING, HARSH SHADOWS, DEEP RED STUDIO BACKGROUND. HIGH FASHION PHOTOGRAPHY, VOGUE STYLE, STYLISH AND SWAG LOOK AND SAD, HIGHLY DETAILED TEXTURE.", img:"images/114.jpg" },
  { id:115, cat:"Cinematic", title:"Red Graphic Poster", prompt:"A black-and-white aesthetic portrait of a stylish me(use my image with accurate face 100%) standards on the in Wall dramatic lighting. He is wearing an oversized dark coat, with messy, voluminous hair partially covering his face. His pose is emotional and introspective, with one hand near his mouth and his head slightlytm turned to the side. Shadow from a window fall across the wall behind him, creating a moody and artistic atmosphere.", img:"images/115.jpg" },
  { id:116, cat:"Cinematic", title:"Black Horse Photo", prompt:"Square 1:1 canvas. Perfect centered circular crop with hard round mask. Outside circle pure black. A circular profile picture design featuring Indian. He is wearing a crisp white button-down shirt and looking intensely at the camera with a serious expression, his right hand raised with fingers touching his temple. The image has a strong monochromatic purple and neon magenta aesthetic.The background features large, translucent block text reading 'dhruv.aieditz' and a horizontal CRT scanline texture overlay. At the bottom, there is sharp, stylized white text that reads \"YOUR NAME\". High contrast, digital fan art style, glowing neon lighting. 100% same face as reference person.", img:"images/116.jpg" },
  { id:117, cat:"Cinematic", title:"Luxury SUV Photo", prompt:"Preserve My face 100% A ultra realistic day shot keer vertical frame\n9:16 retio, of a young Asian man as reference image wearing an wearing washed black, acid-wash streetwear hoodie. and He wears baggy white denim jeans and white green jorden4 sneakers and He wear a Wraparound glasses. leaning casually against the front hood of a A realistic vertical photo of a light blue Porsche 911 GT3 RS (992 generation)", img:"images/117.jpg" },
  { id:118, cat:"Cinematic", title:"Yellow Fashion Poster", prompt:"Create a moody mysterious portrait of my picture.\nKeep the same background and camera angle as per the reference warm golden hour sunlight casting dramatic shadow on a plain wall ensure the strong shadow of the face on the wall is visible ratio 9:16 overall cinematic tone.\nDo not change the pose or any kind of detail, just add sunlight", img:"images/118.jpg" },
  { id:119, cat:"Cinematic", title:"Orange Editorial Style", prompt:"A cinematic portrait of a young man sitting with a relaxed posture, his head slightly tilted down, wearing a color-blocked shirt in muted tones of orange and blue, illuminated by warm, moody lighting. behind him is a large circular orange backdrop resembling a sunset, creating a striking silhouette effect. editorial, soft shadows, artistic composition, minimalistic background, dreamy and introspective mood, high-quality, natural texture and tones.", img:"images/119.jpg" },
  { id:120, cat:"Cinematic", title:"Blue Cinematic Portrait", prompt:"USE MY IMAGE UPLOAD IN A PERSON SITTING ON A LOW, TEXTURED STONE WALL UNDER A VIVID BLUE SKY WITH LARGE FLUFFY WHITE CLOUDS, IN A RELAXED AND INTROSPECTIVE POSE. USING THE REFERENCE IMAGE AS A STRICT AND NON-NEGOTIABLE SOURCE, PRESERVE THE EXACT LIKENESS, FACIAL STRUCTURE, BODY PROPORTIONS, AND NATURAL HAIR OF THE PERSON.\nTHEY ARE WEARING A LOOSE BEIGE KNIT SWEATER WITH BLUE HORIZONTAL STRIPES, BROWN CARGO PANTS, AND HIGH-TOP SNEAKERS. THEY REST COMFORTABLY, ONE ARM DRAPED OVER A BENT KNEE, GAZING SOFTLY TOWARD THE HORIZON.\nNATURAL LIGHTING WITH WARM SUNLIGHT HIGHLIGHTS THE FABRIC TEXTURES AND CREATES REALISTIC SHADOW FALLOFF. THE CINEMATIC COMPOSITION USES A LOW ANGLE TO EMPHASIZE THE DRAMATIC SKY BACKGROUND.\nEDITORIAL FASHION PHOTOGRAPHY, ULTRA-DETAILED SKIN TEXTURE, SHALLOW DEPTH OF FIELD, 85MM LENS, HYPERREALISTIC, MAGAZINE AESTHETIC --AR 3:4 --V 6.0 --STYLE RAW", img:"images/120.jpg" },
  { id:121, cat:"Cinematic", title:"Sunlight Shadow Portrait", prompt:"Dreamy scrapbook collage aesthetic of a confident man, chest-level framing only (mid-torso to head), multiple angles and poses.\nOutfit: oversized burgundy and white striped rugby sweatshirt with structuredcollar, relaxed fit,minimal blacktrousers slightly visible at frame edge.Clean casual winter aesthetic.Added elements: torn paper cut-outs, neutral tape strips, vintage stamps, subtle serif notes, minimal arrows, film strips, soft white grid background.Indoor soft lighting with slight mirror", img:"images/121.jpg" },
  { id:122, cat:"Cinematic", title:"Vintage Car Rooftop", prompt:"4K ultra realistic dark aesthetic mirror portrait of a confident young man standing in front of a minimalist black-framed mirror. He is dressed in a black formal suit layered over a bright white shirt, with a thin silver chain resting elegantly on his collarbone. The pose is relaxed but powerful, one hand in pocket, the other holding a black iPhone 16 Pro Max slightly angled while capturing the mirror reflection. The phone's matte black finish and triple camera detail are clearly visible in the reflection. His wavy hair falls naturally with soft texture and volume. Low key lighting creates dramatic shadows on his face. Background is softly blurred with dark neutral tones. Professional editorial photography, ultra HD clarity, detailed fabric stitching, realistic light reflection on the phone and mirror surface, cinematic mood, Instagram fashioh563 Influencer style, elegant, bold, modern aesthetic.", img:"images/122.jpg" },
  { id:123, cat:"Cinematic", title:"Yellow Glitch Poster", prompt:"Stylize the uploaded image into a powerful artistic portrait using the same face. 9:16 vertical ratio. Dark silhouetted profile facing left. Intense electric blue background. Bold black and red paint explosions, high-contrast textures. Cinematic lighting with deep shadows and sharp highlights. Ultra-HD poster-grade quality. Dramatic mood, clean composition, premium fine-art aesthetic. 100% same face as reference person.", img:"images/123.jpg" }
]
];

/* =========================================================
   STORAGE KEYS
   ========================================================= */
window.WHP_KEYS = {
  OVERRIDES: "whprompts_overrides",
  DELETED:   "whprompts_deleted",
  CUSTOM:    "whprompts_custom",
  SETTINGS:  "whprompts_settings",
  PAGES:     "whprompts_pages"
};

/* =========================================================
   DEFAULT PAGES CONTENT
   ========================================================= */
window.DEFAULT_PAGES = {
  about: {
    title: "About WHprompts",
    subtitle: "Empowering creators worldwide with free, ready-to-use AI photo prompts."
  },
  contact: {
    title: "Contact Us",
    subtitle: "Have a question, feedback, or partnership inquiry? We're here to help."
  },
  privacy: {
    title: "Privacy Policy",
    subtitle: "How we collect, use, and protect your information."
  },
  terms: {
    title: "Terms & Conditions",
    subtitle: "The rules for using WHprompts."
  },
  disclaimer: {
    title: "Disclaimer",
    subtitle: "Important information about our content."
  },
  dmca: {
    title: "DMCA Policy",
    subtitle: "How to submit copyright infringement notices."
  }
};

/* =========================================================
   STORAGE HELPER API
   ========================================================= */
window.WHP = {
  // ---------- Overrides (edits to default prompts) ----------
  getOverrides() {
    try { return JSON.parse(localStorage.getItem(WHP_KEYS.OVERRIDES) || "{}"); }
    catch (e) { return {}; }
  },
  saveOverrides(o) { localStorage.setItem(WHP_KEYS.OVERRIDES, JSON.stringify(o)); },
  setOverride(id, changes) {
    const o = this.getOverrides();
    o[id] = { ...(o[id] || {}), ...changes };
    this.saveOverrides(o);
  },
  removeOverride(id) {
    const o = this.getOverrides();
    delete o[id];
    this.saveOverrides(o);
  },

  // ---------- Deleted (removed default prompt IDs) ----------
  getDeleted() {
    try { return JSON.parse(localStorage.getItem(WHP_KEYS.DELETED) || "[]"); }
    catch (e) { return []; }
  },
  saveDeleted(a) { localStorage.setItem(WHP_KEYS.DELETED, JSON.stringify(a)); },
  addDeleted(id) {
    const a = this.getDeleted();
    if (!a.includes(id)) a.push(id);
    this.saveDeleted(a);
  },
  removeDeleted(id) {
    this.saveDeleted(this.getDeleted().filter(x => x !== id));
  },
  isDeleted(id) { return this.getDeleted().includes(id); },

  // ---------- Custom (user-added prompts) ----------
  getCustom() {
    try { return JSON.parse(localStorage.getItem(WHP_KEYS.CUSTOM) || "[]"); }
    catch (e) { return []; }
  },
  saveCustom(a) { localStorage.setItem(WHP_KEYS.CUSTOM, JSON.stringify(a)); },
  addCustom(p) { const c = this.getCustom(); c.push(p); this.saveCustom(c); },
  updateCustom(id, changes) {
    const c = this.getCustom();
    const i = c.findIndex(p => p.id === id);
    if (i >= 0) { c[i] = { ...c[i], ...changes }; this.saveCustom(c); }
  },
  deleteCustom(id) {
    this.saveCustom(this.getCustom().filter(p => p.id !== id));
  },

  // ---------- Settings ----------
  getSettings() {
    try {
      const s = JSON.parse(localStorage.getItem(WHP_KEYS.SETTINGS) || "{}");
      return { ...this.DEFAULT_SETTINGS, ...s };
    } catch (e) { return { ...this.DEFAULT_SETTINGS }; }
  },
  saveSettings(s) { localStorage.setItem(WHP_KEYS.SETTINGS, JSON.stringify(s)); },
  DEFAULT_SETTINGS: {
    siteTitle: "WHprompts",
    siteBadge: "VIP",
    heroTitle: "Copy-Paste Ready AI Photo Prompts",
    heroSubtitle: "Premium Gemini AI prompts for Boy, Girl, Couple, Family, Diwali, Birthday, Beach & more. Click any card to view & copy instantly.",
    footerText: "Made with 💜 by WHprompts · Powered by Media.io & Gemini AI",
    tryNowUrl: "https://www.media.io/ai/image-to-image?uni_fun_code=image2image_banana_2",
    contactWhatsApp: "+92 317 8267308",
    contactEmail: "waqashamzaofficial@gmail.com",
    contactAddress: "Okara, Punjab, Pakistan"
  },

  // ---------- Pages ----------
  getPages() {
    try {
      const p = JSON.parse(localStorage.getItem(WHP_KEYS.PAGES) || "{}");
      const merged = {};
      Object.keys(window.DEFAULT_PAGES).forEach(k => {
        merged[k] = { ...window.DEFAULT_PAGES[k], ...(p[k] || {}) };
      });
      return merged;
    } catch (e) { return { ...window.DEFAULT_PAGES }; }
  },
  savePages(p) { localStorage.setItem(WHP_KEYS.PAGES, JSON.stringify(p)); },
  setPage(key, data) {
    const p = this.getPages();
    p[key] = { ...p[key], ...data };
    this.savePages(p);
  },

  // ---------- Master merge ----------
  getAllPrompts() {
    const overrides = this.getOverrides();
    const deleted = this.getDeleted();
    const custom = this.getCustom();

    const defaults = window.DEFAULT_PROMPTS
      .filter(p => !deleted.includes(p.id))
      .map(p => ({ ...p, ...(overrides[p.id] || {}), isDefault: true, edited: !!overrides[p.id] }));

    const customs = custom.map(p => ({ ...p, isDefault: false, edited: false }));

    return [...defaults, ...customs];
  },

  // ---------- Backup / Restore ----------
  exportAll() {
    return {
      version: 4,
      exportedAt: new Date().toISOString(),
      overrides: this.getOverrides(),
      deleted: this.getDeleted(),
      custom: this.getCustom(),
      settings: this.getSettings(),
      pages: this.getPages()
    };
  },
  importAll(data) {
    if (!data || typeof data !== "object") throw new Error("Invalid backup file");
    if (data.overrides) this.saveOverrides(data.overrides);
    if (data.deleted) this.saveDeleted(data.deleted);
    if (data.custom) this.saveCustom(data.custom);
    if (data.settings) this.saveSettings({ ...this.DEFAULT_SETTINGS, ...data.settings });
    if (data.pages) this.savePages(data.pages);
  },
  resetAll() {
    Object.values(WHP_KEYS).forEach(k => localStorage.removeItem(k));
  }
};

console.log("✅ WHprompts data loaded:", window.DEFAULT_PROMPTS.length, "defaults");